#!/bin/bash
#title           :aws.sh
#description     :Bash script for AWS work sample.
#author		       :Elliott Ning
#date            :20171114
#version         :1.4

#==============================================================================

# set variables
export blockdevice=
export blockuuid=UUID=

# display variables
echo "device name is $blockdevice"
echo "device uuid is $blockuuid"

#==============================================================================

echo -e "Check the block volume variables and type y to start the script:"
read input
if [ $input == 'y' ]
then

  echo "Mount block volume."
  mkfs -t ext4 $blockdevice
  mkdir /block
  mount $blockdevice /block
  sudo cp /etc/fstab /etc/fstab.orig
  sed -i -e '$blockuuid /block ext4 defaults,nofail 0 2' file
  cd /block

  echo "Update system..."
  yum -y update
  yum -y install yum-utils

  echo "Install software for webserver."
  yum -y install httpd

  echo "Enable firewall to have ports 80 / 443 opened; start and enable webserver."
  firewall-cmd --permanent --add-port=80/tcp
  firewall-cmd --permanent --add-port=443/tcp
  firewall-cmd --reload
    
  echo "Start and enable webserver."
  systemctl start httpd
  systemctl enable httpd


  echo "download content"
  cd /var/www/html/
  wget http://wordpress.org/latest.tar.gz
  chown -R apache:apache /var/www/html/*

  echo "Configure WordPress to use the MySQL database"
  cp wordpress/wp-config-sample.php wp-config.php
  sed -i 's/database_name_here/wordpress/g' wp-config.php

  echo "Enter the URL below in your browser to see the website:"
  IP=`wget http://ipecho.net/plain -O - -q ; echo`
  echo "http://$IP"

else
  echo "Edit the variables and try again"

fi

#EOF
