#!/bin/bash

echo "Step 2: Create MySQL Database and configure WordPress"
echo "Configure MySQL database"
mysql_secure_installation

echo "Create Database for WordPress"
mysql -u root -p

<<MYSQL_SCRIPT
CREATE DATABASE wordpress;
CREATE USER wordpressuser@localhost IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON wordpress.* TO wordpressuser@localhost IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
EXIT
MYSQL_SCRIPT
