#!/bin/bash

echo "Step 2: Create MySQL Database and configure WordPress"
echo "Configure MySQL database"
mysql_secure_installation

echo "Create Database for WordPress"
mysql -u root -p

mysql -e "CREATE DATABASE wordpress;"
mysql -e "CREATE USER wordpressuser@localhost IDENTIFIED BY 'password';"
mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO wordpressuser@localhost IDENTIFIED BY 'password';"
mysql -e "FLUSH PRIVILEGES;"
mysql -e "EXIT"
