#!/bin/bash
#Creator: Elliott Ning - Oracle Cloud Specialist Consultant
#Version: 1.0
#Date: 10/31/2017

#Step0: Check provisioned resource
echo -e "Please make sure all needed resource is provisioned, and type y to continue"
read input
echo "Starting script"

echo "Step1: Download and install WordPress and dependencies"
echo "Enable MySQL repo and install software for MySQL-server"
yum-config-manager --enable ol7_MySQL56

#echo "Update OS"
#yum update -y

echo "Install software for webserver"
yum install httpd -y

echo "Enable firewall to have these ports 80 / 443 added; start and enable webserver"
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload
systemctl start httpd
systemctl enable httpd

echo "Install software for PHP"
yum install php php-mysql php-pdo php-gd php-xml –y
systemctl restart httpd.service

echo "Enable MySQL repo and install software for MySQL-server"
yum install mysql mysql-server -y

echo "Start and enable mysqld"
systemctl start mysqld
systemctl enable mysqld

echo "Get the latest tar ball from wordpress.org and untar the package"
cd /var/www/html/
wget http://wordpress.org/latest.tar.gz
tar zxvf latest.tar.gz
chown -R apache:apache /var/www/html/*
