#!/bin/bash
mysql -uroot -ppassword -e "CREATE DATABASE wordpress"
mysql -uroot -ppassword -e "CREATE USER wordpressuser@localhost IDENTIFIED BY 'password'"
mysql -uroot -ppassword -e "GRANT ALL PRIVILEGES ON wordpress.* TO wordpressuser@localhost IDENTIFIED BY 'password'"
mysql -uroot -ppassword -e "FLUSH PRIVILEGES"
