#!/bin/bash
###################################################################
### CONFIGURATION AREA - ALL PATHS ARE ABSOLUTE, NO TRAILING / ###
###################################################################

# Define the username and password of a user that can create dbs 
# and grant permissions.
user=wordpressuser
password=password

###################################################################
### WORK AREA - DONT EDIT BELOW THIS LINE UNLESS YOU CAN FIX IT ###
###################################################################

die () {
echo >&2 "$@"
exit 1
}

# Check if we have an argument, exit if not
[ "$#" -eq 1 ] || die "Need a db name as argument (only)"

# Create database
mysql -u$user -p$password -e "CREATE DATABASE $1"
mysql -u$user -p$password -e "GRANT ALL PRIVILEGES ON $1.* TO $1_user@localhost IDENTIFIED BY '$1.Pass!'"


# Let the user know something good just happened
echo "Database creation of $1 complete."
echo "Access with username $1_user and password $1.Pass!"
